### ISSUE TITLE
restarting development and criterion's future

### ISSUE THREAD

**Issue by japaric** [bheisler/criterion.rs#55]
I'd like to get criterion back into a usable state, and I'd like to improve the
user experience around it.

Here's my plan so far, input is appreciated and PR are also welcomed.
### Immediate actions: criterion 0.1.0

Basically, release criterion with its current public API, refactor its
internals, further improvements shouldn't break the API.
- [x] land new timing loops #26 
- [x] make compilable on current nightly
- [x] refactor: use the new Instant/Duration APIs (when stable?)
- [x] fix travis
- [x] CI: test on mac. see #70 
- [x] CI: test on windows. see #70 
- [x] documentation: explain output/plots, add examples, how to use in a cargo
  project
- [x] fix Appyevor
- [x] release dependencies
- [x] start making releases.
### Short term: criterion 0.1.x
- [x] refactor: reduce usage of unstable features.
  - Throw away or put simd behind a cargo feature, it's unstable and only works
    with x86_64
  - criterion won't work on stable anytime soon because it depends on
    test::black_box
- [x] colorize output messages
- [x] developer documentation: explain the math
- [x] refactor: proper error handling in internals. bubble up errors and report them instead of panicking/unwrapping
- [x] clippy
- [x] rustfmt
### Future: criterion 0.2

If we are allowed breaking changes, how can we improve the user experience? Some
ideas:
- [x] simplify the public API
  - #26 adds several methods, perhaps all the similarly named methods can be
    replaced with a function that takes enums or some builder pattern.
- [ ] expose errors to user instead of panicking/exiting
- [ ] expose more internals, e.g. return an intermediate struct with the benchmark results
  instead of directly writing the results to disk.
- [ ] move away from gnuplot, produce a web report with interactive plots
- [x] better integration with cargo, output files to target directory, plots
  could live in target/doc

If you used criterion in the past, I'd like to hear about your experience.
- In general, What worked well? And, What didn't work for you?
- How helpful/clear/confusing were the generated plots/the output message?
- Was the performance regression detection reliable, or did you get false
  positives?
- What functionality do you think is missing?
- Any suggestion to improve the user experience?

**Comment by japaric** [comment]
@faern will, hopefully this week, send us some PR to get us close to compiling on a recent nightly. :+1:

**Comment by japaric** [comment]
Next actions:

- publish criterion dependencies
- write great docs
- publish criterion 0.1.0

@faern if you can land the multiple functions benchmarking method before 0.1.0, excellent. If not it can wait until 0.1.1.

**Comment by faern** [comment]
@japaric I did some rebasing of that on top of your latest merge this morning. I will see when I can get it ready. Hopefully within a day.

I have another suggestion. How about we run rustfmt on the entire crate before 0.1.0? My Rust editor runs that automatically on save so I have a hard time to not commit unrelated changes :) Also good to comply to the standards.

**Comment by japaric** [comment]
> @japaric I did some rebasing of that on top of your latest merge this morning. I will see when I can get it ready. Hopefully within a day.

:+1: 

> I have another suggestion. How about we run rustfmt on the entire crate before 0.1.0?

Sounds good to me. But last time I ran `cargo fmt` the source files related to plotting looked really bad; they were heavily indented IIRC.

Something I forgot to mention. What do you think about changing the signature of methods like `Criterion::warm_up_time` to accept a `Duration` instead of a `u64` that represents nanoseconds? We are already using `Duration` internally. It would be the last breaking change before 0.1, or we could hold wait until 0.2 to land it.

I'll be publishing the criterion dependencies time when I get free time.

**Comment by faern** [comment]
PR created: #64 
Except the benchmarking over multiple functions it adds another iter method. Tell me if you rather skip that one..

Yes, we should be consistent and use Duration everywhere. I think we can cram that into this release!

**Comment by faern** [comment]
`cargo fmt` made some plotting stuff weird yes, but that was because the code is a little bit strange from the start :P The correct solution is still to format it, but we might want to save that until it can be refactored into not looking like this.

**Comment by japaric** [comment]
> PR created: #64

Will leave comments over there.

> Yes, we should be consistent and use Duration everywhere. I think we can cram that into this release!

:+1: 

re: cargo fmt. We can put a `#![rustfmt_skip]` on the plotting modules and `cargo fmt` the rest. Let's do that after the other PRs land to avoid rebasing them.

**Comment by faern** [comment]
I did put `#![rustfmt_skip]` on the plot files and ran `cargo fmt`. I didn't want to submit a PR since if it was my project I would want to do such large change myself, but feel free to merge in my master branch if you want to.

What's more left now? I see you did some commits on testing, but didn't check those boxes yet.

**Comment by japaric** [comment]
The CI stuff is done. I forgot to check those boxes. Dependencies have been released to crates.io as well. Only docs are missing. I'm trying to figure out the simplest way to run benchmarks in a cargo project.

**Comment by ms705** [comment]
Hi!

Recent adopter of criterion here -- nice work!

Some comments on things that would be helpful for our (@jonhoo's and my) use case:

> Was the performance regression detection reliable, or did you get false positives?

We would prefer if this the comparison step could be disabled as part of the configuration, or at least if it avoided failing hard. The experiments we're running are often somewhat noisy, and we run multiple benchmarks in sequence, so it's annoying to fail because of a false positive regression on one of them.

> What functionality do you think is missing?

One additional feature (on top of being able to disable the regression testing) that would really help us is the ability to invoke a one-off setup routine, which is only executed once for all benchmarks. 

In our use case, we create a benchmark database and populate it with some basic data, but this can take a while. Having to do it once per benchmark seems wasteful, so we're working around this by having multiple `Criterion::default().bench_function(...)` invocations in a single test routine. However, this is not ideal, because it's now no longer possible for us to run a single benchmark in isolation.

**Comment by hauleth** [comment]
How is it going?

**Comment by jonhoo** [comment]
I'd be happy to invest some time in a PR or two if it would be of any use.
Anything in particular you'd like help with?

**Comment by bheisler** [comment]
Hello everyone! I'm bheisler, and with @japaric's permission I've volunteered to take over maintenance of Criterion-rs. At least to start with, I'll probably be following the plan posted here relatively closely. I hope to wrap up release 0.1 at some point in the next few weeks.

**Comment by mersinvald** [comment]
@bheisler hello, I have a quick question about criterion-rs future: are the overall trend graphs planned?
It would be nice to have a graph showing how the performance evolved throughout development time, not just compared to the previous build. (or am I missing something that is already there?)

**Comment by bheisler** [comment]
Hmm. I haven't really given that one much thought, to be honest. My workflow when benchmarking is more based on the Profile/Tweak/Benchmark loop rather than tracking performance over days or weeks. I'm not sure what one would want in a long-running trend graph or if Criterion.rs is the right place to generate one. On the other hand, I know that some people are using Criterion.rs for that purpose already, so it might make sense for that workflow to be more directly supported.

Can you describe in more detail what you're looking for?

**Comment by mersinvald** [comment]
Okay, mine is structured alike, more or less, but I am constantly running into this scenario:
1) Run benchmark
2) Tweak
3) Run benchmark, see that performance has regressed
4) Now I need to check out initial version and rerun benchmark to be able to compare the next tweak
As benchmarks are quite complex and take much time, this is not very comfortable.

And lastly, having some squished down version of the report in git tree just for sake of seing overall performance trend would be cool, but that's a bit another story.

I'd be happy to see something similar to graphs that Jenkins-Performance has in their Web UI (https://imgur.com/wavTvXf)
Graph legend shown in the picture is just an example.

**Comment by droundy** [comment]
One advantage of the long-term performance graph is that it allows one to easily see beyond the noise.  Yes, you can just sample longer to reduce the noise, but that isn't always feasible.  Also, it allows you to see whether you have fixed a regression.  The short tweak optimization cycle works as long as you're only optimizing, but once you intersperse new functionality it becomes trickier.
